INSERT INTO USER VALUES (1001, SYSDATE(), 'Bruno');
INSERT INTO USER VALUES (1002, SYSDATE(), 'Rafael');
INSERT INTO USER VALUES (1003, SYSDATE(), 'Carlos');

INSERT INTO POST VALUES (1101, SYSDATE(), 'primeiro post qualquer', 1001);
INSERT INTO POST VALUES (1102, SYSDATE(), 'segundo post qualquer', 1001);
